blank_issues_enabled: false
contact_links:
  - name: GitHub Community
    url: https://github.com/orgs/crs-project/discussions
    about: Please ask and answer questions here.
  - name: Website 
    url: https://crs-project.github.io
